### ISSUE TITLE
Error handing of repeated KeyboardInterrupt or other exceptions

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceDesignTeam/roveberrypy#39]
Processes must wait until the end of the next main loop before acting on the quit message. Additional interrupts produce the error:

```
Process ExampleServer-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/austin/roveberrypy/roverprocess/RoverProcess.py", line 61, in run
    self.cleanup()
  File "/home/austin/roveberrypy/roverprocess/RoverServer.py", line 48, in cleanup
    thread.join(0.25)
  File "/usr/lib/python3.4/threading.py", line 1064, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

Due to attempting to join a thread (to kill it) but being blocked by that thread sleeping.

We may need some way to gracefully kill a thread in the middle of a time.sleep(), or by telling the main.py not to accept KeyboardInterrupts until all processes have exited nicely.

_PS: If you add this block in Python 3.5 for diagnostics:_

```
while(self.receiver.is_alive()):
     print("Still alive")
```

_Nothing seems to happen. This works in Python 2.7 (with isAlive())._

**Comment by ottopasuuna** [comment]
I fixed the error that you posted, but there is still the following error when you press ctrl-C twice:
```
ExampleProcess shutting down
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
This isn't too ugly looking and it may be easiest to fix it properly durring a rewrite of the software sometime in the future (Christmas break?).
